### ISSUE TITLE
Implement FREME Cloud

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#106]

**Comment by jnehring** [comment]
Created eureka server in new github repository. Manually deployed it on freme-dev. It runs on freme-dev. Some cosmetic stuff should be done which is not necessary now:
* https://github.com/freme-project/eureka-service/issues/1
* https://github.com/freme-project/eureka-service/issues/2
* https://github.com/freme-project/eureka-service/issues/3
* https://github.com/freme-project/eureka-service/issues/4

Eureka managment UI is available at http://api-dev.freme-project.eu:8761/

**Comment by jnehring** [comment]
Basic cloud workflow implement locally

* Create starter classes
    * eu.freme.Broker starts broker in standalone mode
    * eu.freme.CloudBroker starts broker in cloud mode
    * eu.freme.FremeNER starts FREME NER in standalone mode
    * eu.freme.CloudFremeNER starts FREME NER in cloud mode
* Create dummy FREME NER endpoint: it converts text that you send in post body to upper case
* Create proxy endpoint in cloud broker: it uses feign and eureka to proxy a request to dummy freme ner endpoint

So when I start CloudBroker and CloudFremeNER on my laptop then
* both machines register with eureka on freme-dev
* http://localhost:8081/freme-ner-test with post body "test" calls the freme-ner service directly and returns "TEST"
* http://localhost:8080/freme-ner-proxy?message=testcalls cloud broker that dynamically gets host and ip of cloud freme ner and connects to the service. It also returns "TEST".

**Comment by jnehring** [comment]
This will be implemented in a future version of FREME

**Comment by fsasaki** [comment]
IMO we should put this on the plate for FREME 0.5.

**Comment by jnehring** [comment]
For now this is implemented using the proxy service. FREME cloud is delayed for unknown time and this ticket is outdated
