### ISSUE TITLE
Implement Template Security

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#107]
First solve these issues:

1. https://github.com/freme-project/FREMECommon/issues/6
2. https://github.com/freme-project/FREMECommon/issues/5
3. https://github.com/freme-project/e-Link/issues/43

Then template security can be implemented.

**Comment by ArneBinder** [comment]
Implemented and should work. Perhaps more integration tests are needed, opened [this issue](https://github.com/freme-project/Broker/issues/109).

**Comment by jnehring** [comment]
I reopen this ticket because I believe this is not finished. We will talk about it tomorrow.
