### ISSUE TITLE
Research on https certificate

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#112]
Please research if the https certificate we have is suitable for subdomains: api.freme-project.eu and api-dev.freme-project.eu

**Comment by josauder** [comment]
Wir haben ein single-domain-certificate
![singledomain](https://cloud.githubusercontent.com/assets/12648328/10363923/cc00043c-6db7-11e5-9f4b-86ef7670cb17.png)



Wir brauchen eins für mehrere Subdomains oder win wildcard Zertifikat.
Godaddy bietet folgendes an:
https://de.godaddy.com/web-security/ssl-certificate
https://de.godaddy.com/help/was-ist-ein-wildcard-ssl-zertifikat-567

**Comment by jnehring** [comment]
I will read that and kindly ask godadfy for a second single domain certificate or a wildcard certificate.
