### ISSUE TITLE
Integration test for e-Link

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#114]
We need a reliable integration test for e-Link. The problem is that e-Link relies on SPARQL endpoints / external services which are not always available. The integration tests for the broker start up another REST API endpoint, that returns a static RDF upon each request. This is our dummy SPARQL endpoint.

The integration test for e-Link starts this SPARQL endpoint, creates a template that queries this endpoint and performs queries to e-Link for testing.

In that way we can create an integration test for e-Link that does not rely on external services, is very light weight and can start up quickly.

**Comment by jnehring** [comment]
One idea for later: We can apply the same technique to integration tests for dbpedia spotlight, tilde e-terminology and tilde e-translation which suffer from the same problem.

**Comment by jnehring** [comment]
In the commit attached to this issue I put sample code for a mockup API endpoint. This can provide the basis for the mockup endpoints.

**Comment by ArneBinder** [comment]
implemented in the `integration-tests` branch and works fine.

**Comment by ArneBinder** [comment]
merged into master.
