### ISSUE TITLE
Write integration test for /e-link/explore endpoint

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#117]
It was created in issue https://github.com/freme-project/e-Link/issues/41
Wait until documentation is ready: https://github.com/freme-project/Documentation/issues/90

**Comment by m1ci** [comment]
the documentation is ready

**Comment by jnehring** [comment]
Please implement it using a mockup sparql endpoint, the same way #114 is implemented.

**Comment by jnehring** [comment]
Please test LDF version also. The same issue like https://github.com/freme-project/e-Link/issues/51 might occur.

**Comment by ArneBinder** [comment]
I'm trying to write the mockup endpoint `/mockups/ldf` but could not get to use it with `/explore`. @m1ci perhaps you could help me: what content should the mockup endpoint provide to work together with e-link /explore? There is [this test](https://github.com/freme-project/Broker/blob/integration-tests/src/test/java/eu/freme/broker/integration_tests/ELinkSecurityTest.java#L263-L279) in the `integration-test` branch of broker, which failes. The [sparl mockup test](https://github.com/freme-project/Broker/blob/integration-tests/src/test/java/eu/freme/broker/integration_tests/ELinkSecurityTest.java#L243-L261) seems to work. The mockup endpoints are implemented [here](https://github.com/freme-project/Broker/blob/integration-tests/src/test/java/eu/freme/broker/integration_tests/mockups/ELinkMockupEndpoint.java) so far.
Thanks in advance for any help!

**Comment by m1ci** [comment]
/explore provide triples associated with the resource. So you can just mockup some triples which should be returned.

**Comment by jnehring** [comment]
Arne please try a GET request to 

http://fragments.dbpedia.org/2014/en?subject=http%3A%2F%2Fdbpedia.org%2Fresource%2FBerlin&predicate=&object=

and set Accept header to `text/turtle`

**Comment by ArneBinder** [comment]
implemented in the branch and works fine.
