### ISSUE TITLE
Update just the metadata of a template

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Broker#119]
should we provide this? seems to be cool, but we have to know how to send a PUT request with empty body. Or ugly: using a dummy body (I really don't want to do this).

**Comment by m1ci** [comment]
the HTTP Patch method should be used for partial modifications
see http://tools.ietf.org/html/rfc5789

**Comment by jnehring** [comment]
There is more important things to do right now. Lets leave this for later.

**Comment by ArneBinder** [comment]
Ok.
@m1ci thanks for the hint!

**Comment by jnehring** [comment]
I think we do not need this feature
