### ISSUE TITLE
Check on write access in e-Link

### ISSUE THREAD

**Issue by ghsnd** [freme-project/Broker#123]
(Why) is [this line of code](https://github.com/freme-project/Broker/blob/38369518c9126afff079e74b65e122f0293a9717/src/main/java/eu/freme/broker/eservices/ELink.java#L280) in ELink.java necessary? The write permission is checked later on by the `save` and `updateOwner` methods. Or is it just to speed things up?

Just wondering because I'm implementing `update` for pipelines...

**Comment by jnehring** [comment]
It calls the AccessDecisionManager: https://docs.spring.io/spring-security/site/docs/3.0.x/reference/authz-arch.html

Let me know on Skype when you need further assistance. The line of code you mentioned was written by Arne who is unfortunately not at DFKI today but I think I can give more explanation when needed.

**Comment by ghsnd** [comment]
Thanks Jan, but it's OK. I know what it does, but since the same function is called later in other functions, I thought it was not necessary here.

**Comment by jnehring** [comment]
@ArneBinder please check if this line is really necessary and delete it if not.

**Comment by ArneBinder** [comment]
> Or is it just to speed things up?
Yes, otherwise the template construction code would be unnecessarily executed. But it's not really important, I think we can delete it also. Perhaps, this would be a better design.
