### ISSUE TITLE
Implement changes to Tildes API

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#125]
As written in the Email

**Comment by andish** [comment]
**e-Terminology** :
* mode – full/annotation    - [optional, if omitted, then default is ‘full’]                                     
```@RequestParam(value = "mode", defaultValue = "full") String mode```
* collection – [optional, if given, then filters anotation only from that collection]   
```@RequestParam(value = "collection", required = false) String collection```
* key - user submitted token for this servise [optional, include only, if user has been registered the token]
* authentication – please add static header to let us now that this request is from FREME broker server

 ```
.queryString("mode", mode)
.queryString("collection", collection)
.queryString("key", token)
.header("Authentication", "Basic RlJFTUU6dXxGcjNtM19zJGN1ciQ=")
```
 
**e-Translation**:
* system – when any BC partner will be ready to use its own system then they must provide this system id. [optional, if omitted then source and target language and domain parameter is used]
```@RequestParam(value = "system", required = false) String system```
* enable ‘domain’ parameter
* key - user submitted token for this servise [optional, include only, if user has been registered the token]
* authentication – please add static header to let us now that this request is from FREME broker server

 ```
.queryString("system", system)
.queryString("domain", domain)
.queryString("key", token)
.header("Authentication", "Basic RlJFTUU6dXxGcjNtM19zJGN1ciQ=")
```

**Comment by ArneBinder** [comment]
Implemented. The header "X-Auth-Token" is used as token.

**Comment by jnehring** [comment]
> The header "X-Auth-Token" is used as token.

Actually the FREME key submitted via X-Auth-Token and the tilde key submitted via "key" are two different things. One authenticates against FREME and the other authenticates against Tildes API. @ArneBinder do we need to change the implementation?

**Comment by andish** [comment]
With token I mean using described keys here:
https://github.com/freme-project/technical-discussion/issues/61
@jnehring What is the status of implementation of this?

**Comment by ArneBinder** [comment]
Ok, I switched to query parameter "key" as token. It should work now. 
@andish Please close, if it's all right.
