### ISSUE TITLE
Suppress Exceptions in Integration Tests

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#126]
In the integration-test branch

* Create Spring Bean FREMEExceptionHandler in eu.freme.broker.tools
* Register it in eu.freme.broker.FremeCommonConfig
* Move exception handler from BaseRestController to FREMEExceptionHandler
* Add methods to FREMEExceptionHandler
    * addExpectedException( Class extends Exception )
    * clearExpectedExceptions()
* Try out that spring bean in UserControllerTest and suppress all expected AccessDeniedExceptions

**Comment by jnehring** [comment]
While working on another issue I created `eu.freme.broker.tools.ExceptionHandlerService`. You can use this implementation instead of your the `FREMEExceptionHandler` mentioned in this issue.

**Comment by ghsnd** [comment]
Would it make sense to change the method signature

    public ResponseEntity<String> handleError(HttpServletRequest req, Exception exception)

into

    public ResponseEntity<String> handleError(HttpServletRequest req, Throwable exception)

or is this overkill?

**Comment by jnehring** [comment]
Good idea. Throwable is actually better then Exception. I changed it.

**Comment by jnehring** [comment]
@josauder we were talking the other day about how to suppress expected exceptions that are not thrown but explicitly send to the logger in the source code by something like `logger.error("caught exception", exception)`.

I came upon this article: http://blog.trifork.com/2011/08/23/filtering-specific-exceptions-when-using-log4j/

Please try implementing this. It uses the log4j tooling and is therefore way better then the homebrown solution that I suggested in our conversation.

**Comment by josauder** [comment]
This is now working in `integration-tests` branch.

It is implemted as part of EServiceTest (at the very bottom).

When running tests, e.g. calling `loggerIgnore(eu.freme.broker.exception.AccessDeniedException)` will prevent logging of all AccessDeniedExceptions until `loggerUnignore(eu.freme.broker.exception.AccessDeniedException)` is called. After that, these Exceptions will be logged normally again.

**Comment by jnehring** [comment]
Thanks!

Next steps
* add function "clearExpectedExceptionFilter()"
* add some documentation in comments in the codes
* apply filter to all appenders, not only to the first
* unignore usercontrollertest, ignore the accessdeniedexceptions
* add "INFO" log message "suppressed exception: ..." with the full class name of the exception (if possible)

**Comment by jnehring** [comment]
Is this task finished?
