### ISSUE TITLE
anonymous users can guess a list of real users of Freme server with method Delete User

### ISSUE THREAD

**Issue by andish** [freme-project/Broker#127]
curl -X DELETE --header "Accept: application/json" "http://api-dev.freme-project.eu/current/user/milan"

 as I guessed this as an existing user, I got response
```
  "message": "Access is denied",
  "error": "Unauthorized",
  "status": 401,
```
if I try to delete non-existing user, I get response:
```
 "path": "/user/milans",
  "message": "User not found",
  "error": "Bad Request",
  "status": 400,
```

So - at first should be unauthorized event, only for authorized requests should return 'User not found'

**Comment by jnehring** [comment]
I think that this is not a problem. The security concept does not consider user names as sensitive information. You can also read usernames by e.g. get all templates which returns the owner of the templates.
