### ISSUE TITLE
Supporting e-Entity from browser

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/Broker#131]
Our collegue works on integrating FREME services in his authoring environment. From the browser he calls e-Translate and e-Entity. E-Translate seems to work well, but with e-Entity he gets an error related to CORS. This only happens when requesting `text\html` as output. When asking for e.g. JSON, it works. The input is also `text\html`.

A discussion about this can be found [here](http://www.html5rocks.com/en/tutorials/cors/#toc-handling-a-not-so-simple-request).

**Comment by ghsnd** [comment]
See als [CORS support in Spring](https://spring.io/blog/2015/06/08/cors-support-in-spring-framework)

**Comment by m1ci** [comment]
CORS should be already support by all FREME services.
@pheyvaer do you have any info on the differences in the response headers from the call with `text/html` and requests with other formats?

**Comment by pheyvaer** [comment]
This is what Chrome tells us about the request:
```
#General
Remote Address:178.254.26.119:80
Request URL:http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all
Request Method:OPTIONS
Status Code:400 Bad Request

#Response Headers
Access-Control-Allow-Headers:x-requested-with, content-type
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3600
Connection:close
Date:Wed, 04 Nov 2015 11:35:33 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

#Request Headers
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,nl;q=0.6
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:api-dev.freme-project.eu
Origin:http://localhost
Pragma:no-cache
Referer:http://localhost/pages/contents
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

#Query String Parameters
informat:text/html
outformat:text/html
language:en
dataset:dbpedia
mode:all
```
In order to do CORS `OPTIONS` should be supported, but it is not.

**Comment by andish** [comment]
This can be reproduced also from Documentation page. set informat=text and outformat=text (from dropdowns) and it gives an error.
header says that there is 400 error, but body that 500.
*Headers*
```
{
  "date": "Wed, 04 Nov 2015 11:58:03 GMT",
  "via": "1.1 QUIGON",
  "x-content-type-options": "nosniff",
  "access-control-max-age": "3600",
  "proxy-connection": "Keep-Alive",
  "connection": "Keep-Alive",
  "content-length": "229",
  "x-xss-protection": "1; mode=block",
  "pragma": "no-cache",
  "server": "Apache-Coyote/1.1",
  "x-frame-options": "DENY",
  "access-control-allow-methods": "POST, GET, OPTIONS, DELETE",
  "content-type": "application/json;charset=UTF-8",
  "access-control-allow-origin": "*",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "access-control-allow-headers": "x-requested-with, content-type",
  "expires": "0"
}
``` 
* Body* 
```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-entity/freme-ner/documents",
  "message": "HTTP 500 Internal Server Error",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1446641938088
}
```

**Comment by m1ci** [comment]
There is filter implemented for support for CORS
see https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/tools/CORSFilter.java#L41-L46

Maybe @jnehring knows more about this.

**Comment by jnehring** [comment]
I could not reproduce the problems. Which call exactly did your colleague do? Can he share the Javascript that he used?

@pheyvaer wrote
> In order to do CORS OPTIONS should be supported, but it is not.

The response you posted has one line saying `Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE`. I think this says that this request supports OPTIONS for CORS.

@andish wrote
> This can be reproduced also from Documentation page. set informat=text and outformat=text (from dropdowns) and it gives an error.

Which API call did you try? We do not support outformat=text, when this is an option for outformat in the api documentation then it is a mistake.

@m1ci wrote
> There is filter implemented for support for CORS
see https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/tools/CORSFilter.java#L41-L46

This is the part of the broker that enables CORS for FREME. It adds these 4 lines the the header of every HTTP response:

```
Access-Control-Allow-Headers:x-requested-with, content-type
Access-Control-Allow-Methods:POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3600
```

**Comment by andish** [comment]
I tried Post to /e-entity/freme-ner/documents. and there is a lot of formats in outformat dropdown

![image](https://cloud.githubusercontent.com/assets/11315268/10939241/dd9589cc-8308-11e5-8479-a861a720eccd.png)

**Comment by jnehring** [comment]
I raised https://github.com/freme-project/Documentation/issues/134 to remove outformat=text in POT /e-entity/freme-ner/documents

**Comment by bjdmeest** [comment]
The `OPTIONS`-part doesn't work using this javascript

```
$.ajax({
    method: 'POST',
    headers: {'Content-Type': 'text/html', Accept: 'text/html'},
    data: encodeURIComponent('<p>Paris the city.</p>'),
    url: 'http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all'
})
```

but it does using _this_ javascript

```
$.ajax({
    method: 'POST',
    headers: {'Content-Type': 'text/html', Accept: 'text/n3'},
    data: encodeURIComponent('<p>Paris the city.</p>'),
    url: 'http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=html&outformat=html&language=en&dataset=dbpedia&mode=all'
})
```

However, the actual POST fails with the second javascript because of the wrong parameters. As soon as one of the `informat` or `outformat` parameters has `text/html`, OPTIONS fails when used in the browser.

> Tested in Chrome, jQuery 1.10

**Comment by jnehring** [comment]
I could reproduce the bug. The first code example produced "Response for preflight has invalid HTTP status code 400" on Google Chromes JS console.

I fixed a bug: The e-Internationalization filter performs some input validation on the pre-flight request and throws "400 - bad request" because there is no post body in the pre-flight request. So I disabled e-Internationalization filter for all OPTIONS requests. Now I can run your code example without errors.

I installed the patch on freme-dev. @bjdmeest please try again.

**Comment by bjdmeest** [comment]
Works like a charm, thanks!

**Comment by bjdmeest** [comment]
The bug shown by https://github.com/freme-project/Broker/issues/131#issuecomment-153731180 is back

**Comment by jnehring** [comment]
I will fix the bug.

**Comment by jnehring** [comment]
I could not reproduce the bug. When I executed your jQuery I got back "bad request". "html" is not a valid value for "informat". it should be "text/html". Can you please check again if the bug is really a CORS issue?

Here is the HTML I used to check this - I added .txt to the extension so I can attach it to the GitHub.

[cors-bug.html.txt](https://github.com/freme-project/Broker/files/257412/cors-bug.html.txt)

**Comment by bjdmeest** [comment]
Hmm, indeed, it might have been related to https://github.com/freme-project/e-services/issues/12, apologies for the duplicate issue, I consider this fixed now, thanks!
