### ISSUE TITLE
Problem with Tilde MT API

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#132]
This POST request

URL `https://services.tilde.com/translation/?sourceLang=en&targetLang=ru`
Headers:
```
Accept: application/x-turtle
Content-Type: application/x-turtle
```
Body:
```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema# > .
@prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core# > .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf# > .
@prefix xsd: <http://www.w3.org/2001/XMLSchema# > .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns# > .
<http://freme-project.eu/ >
  a nif:String , nif:RFC5147String , nif:Context ;
    nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
    nif:endIndex    "11"^^xsd:nonNegativeInteger ;
    nif:isString    "translate me"@en ;
```

produces status code 500 and

```
{
    "Message": "An error has occurred."
}
```

The same error occurs on terminology API when I exchange the URL with `https://services.tilde.com/Terminology/?sourceLang=en&targetLang=ru&domain=`

**Comment by andish** [comment]
Yes, it shoud return 406 error instead of 500 error

**Comment by jnehring** [comment]
Why 406? Is the language pair not supported?

**Comment by andish** [comment]
This is not valid turtle:
1) sentence not ended. must end with '.' not ';'
2) URI cannot contain spaces. See prefix namespaces. everything between < and > is treated as uri.

**Comment by jnehring** [comment]
Sorry this was my fault.
