### ISSUE TITLE
Write mockup integration tests

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#133]
Subtasks

#117 
#114 
#124 

See also [Spring Boot externalized configuration](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html). Example of externalized config in eu.freme.broker.security.SecurityConfig

**Comment by ArneBinder** [comment]
@josauder what's the state of these issues? Could you give a short explanation what you already implemented and what should be done to adapt e-link and the related integration-test with respect to your changes in e-Entity? Can we merge the current master into the branches mentioned in #124 (if it's not already done)?

**Comment by josauder** [comment]
* ELinkSecurityTest tests against `localhost/sparql`
* ELinkTest ( which should be merged into ELinkSecurityTest once it works) only tests the `e-link/explore` function against the endpoints on localhost: it works with `sparql` but not with `ldf`, you could try looking into that.
* DBPediaSpotlightTest tests against the current installation of the `e-entity` repo on your machine - in the `configurableEndpoint` branch run `mvn install` and the Broker will test against the sparql endpoint on your localhost. This could easily be done for FremeNERTest as well - it shoud be configurable the same way that DBPediaSpotlightTest is. Note that resolving dependencies in Intellij will override your local installation of `e-entity` repo

**Comment by ArneBinder** [comment]
@josauder cool, thanks!

**Comment by josauder** [comment]
@ArneBinder The FremeNERTest function `testDatasetManagement` succeeds although various errors are thrown - if these are intended you can use `loggerIgnore(<exception-class-name>)` as described in #126. If you want to suppress closely related Exceptions with one call to the function, it is easiest to create an alias as done [here](https://github.com/freme-project/Broker/blob/integration-tests/src/test/java/eu/freme/broker/integration_tests/EServiceTest.java#L61)

**Comment by ArneBinder** [comment]
Sounds good, I'll have a look at this.

**Comment by ArneBinder** [comment]
@jnehring the tests are successfully integrated into the `integration-test` branch. Should I merge into the master?

**Comment by ArneBinder** [comment]
merged & deleted branch `integration-tests`.
