### ISSUE TITLE
Limit on output?

### ISSUE THREAD

**Issue by ghsnd** [freme-project/Broker#135]
Is there a limit on the output of a service? I have this issue (encountered as a step while creating a semantic e-pub):

Send an HTML page to e-Entity and request HTML as output:

    curl -vX POST --header "Content-Type: text/html" --header "Accept: text/html" -d '@administration.txt' "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all"

where administration.txt is actually an HTML file (GitHub doesn't allow HTML's to be uploaded) that can be found [here](https://github.com/freme-project/Broker/files/29975/administration.txt).

The curl command does not get the whole body at once: it outputs

```
...
< Content-Type: text/turtle;charset=UTF-8
< Content-Length: 104247
< Date: Mon, 09 Nov 2015 13:05:35 GMT
< 
[part of the body]
```

then waits a long time, and then outputs:

```
* transfer closed with 21564 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 21564 bytes remaining to read
[rest of the body]
```

Trying this on the api-doc test pages even fails completely. Also note that the Content-Type sais text/turtle though it is HTML (as requested).

If you check the server logs, it seems the complete body is sent and the content type is indeed txt/html:

    DEBUG   2015-11-09 14:19:43,004 [http-nio-8080-exec-8] com.github.isrsal.logging.LoggingFilter  - Request: request id=8; content type=text/html; uri=/e-entity/freme-ner/documents?language=en&dataset=dbpedia&mode=all; payload=[the whole body]" 

Is this a bug, or am I doing something wrong here?

**Comment by jnehring** [comment]
I will look into this but I cant promise to give a good answer today. And until wednesday I am on the FREME hackathon.

It looks like a dublicate of https://github.com/freme-project/e-Internationalization/issues/27

**Comment by ghsnd** [comment]
> It looks like a dublicate of freme-project/e-Internationalization#27

It is. I'm sorry :)
