### ISSUE TITLE
Curl sample for e-terminology

### ISSUE THREAD

**Issue by xFran** [freme-project/Broker#139]
I was asked to open an issue with the curl command with the same params that I'm using in Wripl's app.

The test file 
[freme.txt](https://github.com/freme-project/Broker/files/37866/freme.txt)
Is the way how I receive the data. Believe me or not in the file is some real text in it.  "We are in now way affiliated with the FAI or any of the leagues we cover. We are a totally independent media company.We also aim to cover all other leagues in Ireland and will be expanding our in-depth coverage of those leagues soon."

cUrl command:
```
 curl  -v -d @freme.txt -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api.freme-project.eu/0.4/e-terminology/tilde?informat=text&outformat=json-ld&source-lang=en&target-lang=en&mode=annotation"
```

You will get something like this:
```
{
  "@graph" : [ {
    "@id" : "_:b0",
    "label" : {
      "@language" : "en",
      "@value" : "strong"
    },
    "taConfidence" : "0.61"
  }, {
    "@id" : "_:b1",
    "label" : {
      "@language" : "en",
      "@value" : "strong"
    },
    "taConfidence" : "0.61"
  }, {
    "@id" : "_:b10",
    "label" : [ {
      "@language" : "en",
      "@value" : "Style"
    }, {
      "@language" : "en",
      "@value" : "style"
    } ],
    "taConfidence" : "0.2986"
  }, {
    "@id" : "_:b100",
    "label" : {
      "@language" : "en",
      "@value" : "strong"
    },
    "taConfidence" : "0.61"
```
So I have to filter the content before sending it. Actually I have it. I'm testing the filter now.
If is there something wrong with the parameters please let me know.

Thank you.

**Comment by xFran** [comment]
Actually this is the cUrl:
```
curl  -v -d @freme.txt -X POST --header "Content-Type: text/plain" --header "Accept: text/plain" "http://api.freme-project.eu/0.4/e-terminology/tilde?informat=text&outformat=json-ld&source-lang=en&target-lang=en&mode=annotation"
```

**Comment by m1ci** [comment]
The Accept header is wrong. You need to specify `application/ld+json `
Anyway, the accept header will not influence the results since you specified the outformat parameter which actually overwrites the Accept header.

I seem strings like "strong", "style", ... spotted as terms. These are actually HTML markup elements. You need to clean the content from such markup before sending it to any FREME NER service.

**Comment by xFran** [comment]
I'm testing right now the filter I wrote. Thank you @m1ci .

**Comment by xFran** [comment]
Just wondering. Why "strong" "term" for instance cames multiple times?

**Comment by m1ci** [comment]
> Just wondering. Why "strong" "term" for instance cames multiple times?

Because it occurs in multiple locations in the document.

**Comment by xFran** [comment]
```
            [@id] => _:b9
            [label] => Array
                (
                    [@language] => en
                    [@value] => ANDing
                )

            [itsrdf:taConfidence] => 0
```

This "ANDing" show up in every request. Is that OK?

**Comment by m1ci** [comment]
thats weird. There is not "ANDing" term in the text.
maybe @andish  can help you with this.

**Comment by xFran** [comment]
Cool. Now I tried again and is not. :)

**Comment by xFran** [comment]
I can't reproduce it again. I will ask @andish if show up again. Thank you anyway.
