### ISSUE TITLE
Blacklist usernames

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#141]
The usernames "anonymous" and "authenticated" are reserved. When a user registers with these names then it will conflict with the [rate limiting filter](https://github.com/freme-project/technical-discussion/issues/91).

Please create a hard coded blacklist in the UserController that forbids the registration of these usernames.

**Comment by josauder** [comment]
forbidden:

* ROLE_USER
* ROLE_ADMIN
* ROLE_ANONYMOUS
