### ISSUE TITLE
Implement filter tool

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#143]
Please implement a Spring MVC filter. @josauder just implement a filter so he can help you with the basic setup.

The filter should evaluate if a query string parameter `filter` is set. If yes, the filter becomes active.

It takes the output of a the request and runs a filter against it. Each filter query consists of a name and a SPARQL query. In the first version there is only one filter called "extract-entities-only". It runs a SPARQL query that extracts all objects of triples with "itsrdf:taIdentRef" property. The output will be returned in SPARQL result format in JSON.

In a later version the filter should also be exposed via its own endpoint also. So please create a Java API that takes NIF and the filter name as input, then applies the filter and returns the JSON output. In that way we can reuse this functionality.

**Comment by jnehring** [comment]
You can use our SPARQL endpoint: http://rv2622.1blu.de:8890/sparql . Set graph iri to "http://localhost:8890/test-jan"

**Comment by fsasaki** [comment]
@jnehring , do you have an example CURL request, e.g. chain of e-Entity > e-Link, then deploying the filter?

**Comment by ArneBinder** [comment]
I've implemented a simple version of the postprocessing filter: extract-entities-only in the postprocessing-filter branch.
But I'm not sure about the response format. Should we return triples? Or just a (pure) JSON list of tuples? At the current implementation a graph of triples (serialized jena model) will be returned, in the same RDF format as given via outformat.

**Comment by ArneBinder** [comment]
Implemented a FilterController to manage filters and to execute simple sparql filters.

Workflow:
1) Create the filter `extract-entities-only` by querying `POST http://api-dev.freme-project.eu/filter/extract-entities-only` with postBody:
```
PREFIX itsrdf: <http://www.w3.org/2005/11/its/rdf#>
CONSTRUCT {?s itsrdf:taIdentRef ?o} WHERE {?s itsrdf:taIdentRef ?o}
```
to create the filter `extract-entities-only`.
NOTE: Don't forget to authenticate before.

2) Use the postprocessing filter, for instance with e-link: 

`POST http://api-dev.freme-project.eu/e-link/documents/?informat=turtle&outformat=turtle&templateid=1&filter=extract-entities-only`

**Comment by jnehring** [comment]
Thanks @ArneBinder . Nice work. But one thing about the outformat: The first version of the filter should return result format, this is a flat JSON list - so you should not use a SPARQL CONSTRUCT query but a normal query.

But in a future version this filter should also support SPARQL CONSTRUCT queries and graphs as output . So maybe you comment out the code for SPARQL CONSTRUCT queries so you can re-use it later when

**Comment by jnehring** [comment]
Please add a filter called "terminology-terms-only" with this SPARQL:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select  (lang(?anchorOf) as ?language) (str(?anchorOf) as ?anchor) ?confidence (GROUP_CONCAT(DISTINCT ?label;SEPARATOR = ", ") AS ?new_label) (GROUP_CONCAT(DISTINCT ?uri;SEPARATOR = ", ") AS ?new_uri) where {
 ?term <http://www.w3.org/2005/11/its/rdf#term> "yes".
 ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#annotationUnit> ?annotationUnit .
  ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#anchorOf> ?anchorOf.
 ?annotationUnit rdfs:label ?label.
 ?annotationUnit <http://www.w3.org/2005/11/its/rdf#taConfidence> ?confidence.
 ?term <http://www.w3.org/2005/11/its/rdf#termInfoRef> ?uri
}
group by  ?annotationUnit ?confidence ?anchorOf ORDER by desc ( ?confidence )
```

**Comment by jnehring** [comment]
Please find out if these output formats for result format are easy to integrate:

* JSON
* XML
* CSV
Find out proper mime types and make your filter understand these mime types.

Also wrap the HttpRequest so it overrides the parameter "outformat" and header "Accept" to be always turtle. Then the underlying endpoint produces turtle which is converted by the filter to the outformat the user specified.

**Comment by ArneBinder** [comment]
@jnehring for the usecase TURTLE --> XML (via filter) EInternalization throws an error, because of [these lines](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/tools/internationalization/EInternationalizationFilter.java#L170-L178).

**Comment by jnehring** [comment]
@ArneBinder please write an unit test that reproduces the bug. Then create an issue in broker repo and assign it to me

**Comment by ArneBinder** [comment]
Implemented and merged into the master.

**Comment by jnehring** [comment]
So this issue is finished except for the bug in #150?

**Comment by ArneBinder** [comment]
I think so.
