### ISSUE TITLE
Implement logging filter

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#144]
Please create a logging filter. Copy this source code:

https://github.com/isrsal/spring-mvc-logger

Then perform these tasks

* Change package name to eu.freme.tools.logging-filter
* Add a notice in the header of the source code files mentioning where they come from
* Add whitelist of formats that are logged. Only POST bodies with contents from the whitelist are logged. The whitelist is compared to the "informat" or "Content-Type" parameter. The whitelist should be configurable via a CSV list in application.properties via the parameter freme.logging-filter.formats. Add all RDF serialization formats to the whitelist.
* Add a configurable parameter freme.logging-filter.max-request-size which configures the maximum length of the post body that will be logged, in kb. When this is set to 500 kb then only the first 500 kb of a request will be logged.
* Remove existing logging filter from pom.xml and from log4j.properties

**Comment by josauder** [comment]
This is now implemented:
In `application.properties` you can set the following properties:
`loggingfilter.maxsize`: maximum character length of each message getting logged. Defaults to 1000
`loggingfilter.whitelist`: names of formats that will be logged. Example: `text/turtle, application/x-turtle, turtle` will lead to only turtle requests and responses being logged. If this parameter is not given, the LoggingFilter will find the `RDFSerializationFormats` and enable logging for all key-strings.

I suggest we wait for https://github.com/freme-project/Broker/issues/147 until we close this issue.

**Comment by ArneBinder** [comment]
@josauder could you add the source code files to the [exclude section](https://github.com/freme-project/Broker/blob/master/pom.xml#L241-L248) of the apache maven license plugin? Afterwards, we have to add the headers manually. Thanks!

**Comment by jnehring** [comment]
Related bug in #148

**Comment by josauder** [comment]
I think we can close this issue for now
