### ISSUE TITLE
Unit tests disappeared?

### ISSUE THREAD

**Issue by ghsnd** [freme-project/Broker#145]
Some unit tests, in particular pipelining tests, have disappeared since [build 596](http://rv1443.1blu.de:8082/job/Broker/eu.freme$Broker/596/). I want to develop something and see if it still works. Are they going to come back?

In package eu.freme.broker.integration_tests.pipelines:

* EntityLinkTerminologyTest
* EntityLinkTest
* EntityLinkTranslationTest

**Comment by josauder** [comment]
Seems like they were lost with 4ce0d3de9b371bede2b254ce8511409d2a387e2e albeit not being in the changelog.

I will readd them

**Comment by ghsnd** [comment]
OK, thanks!

**Comment by josauder** [comment]
There they are. Sorry for the inconvenience
