### ISSUE TITLE
Failed unit test in broker

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#146]
There is a failing unit test of the broker that causes unstable builds in Jenkins. The problem occured first time after a commit by @ghsnd 

http://rv1443.1blu.de:8082/job/Broker/624/console

@ghsnd can you please take a look at this?

**Comment by ghsnd** [comment]
Yes, the problem is

    org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://rv2622.1blu.de:8081/api/datasets/integration-test-dataset":Connection refused

Since a few days, this service from e-Entity is down or unreachable...
You can see this e.g. also by asking for the data sets:

    curl -X GET --header "Accept: application/json" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets"

@m1ci can you take a look at this?

**Comment by jnehring** [comment]
Indeed FREME NER has crashed on freme-worker. I created https://github.com/freme-project/freme-ner/issues/55

**Comment by m1ci** [comment]
Dev FREME NER is up and running again. Sorry for the inconvenience.

**Comment by jnehring** [comment]
problem fixed
