### ISSUE TITLE
Wrong Content-Length Header for requests after EInternationalization Filter

### ISSUE THREAD

**Issue by josauder** [freme-project/Broker#148]
For example when running the EInternationalizationTest:
The EInternationalizationFilter is invoked and calls `filterchain.doFilter(bssr, res)` [here](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/tools/internationalization/EInternationalizationFilter.java#L241) with a request that has an empty body but that has the Content-Length of 2127.

I suggest we set this header correctly to 0, this is more consistent and we won't have to make a special case in the LoggingFilter

**Comment by jnehring** [comment]
I can see that the EInternationalizationFilter should change the content length. But I do not see why it should set content length to 0. EInternationalizationFilter converts the input from various formats to turtle and puts the turtle in the body. Therefore the content-length should be the length of the turtle file. We should calculate the new content length and override the content-length in BodySwappingServletRequest.

@josauder what do you think? We can discuss this tomorrow in the office.

**Comment by jnehring** [comment]
The solution is to set the content type header to the right value when e-Internationalisation changes to request body.

**Comment by jnehring** [comment]
I tested it and the content length is already set correctly by the einternationalisation filter:

https://github.com/freme-project/basic-services/blob/master/filters/internationalization-filter/src/main/java/eu/freme/bservices/filters/internationalizationfilter/InternationalizationFilter.java#L295
