### ISSUE TITLE
Filter tool API endpoints

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#149]
For the filter tool implemented in #143 , management API are already created. Next steps

Set URLs:

* URLs for management
    * POST /toolbox/filter/manage/{filter-name}
    * DELETE /toolbox/filter/manage/{filter-name}
* URLs for using the filter
    * POST /toolbox/filter/documents/{filter-name}

Other next steps:

* Add integration tests
* Create API documentation for the 5 endpoints in documentation repository

**Comment by ArneBinder** [comment]
Implemented integration test and merged into master.
