### ISSUE TITLE
[e-translate]: GET language pairs

### ISSUE THREAD

**Issue by ghsnd** [freme-project/Broker#153]
A handy feature for a future release: possibility to get the language pairs by sending a (GET) request. This allows tools (e.g., our CKEditor plugin ;) ) to automatically get the possible language pairs, which has to be hardcoded at this moment.

**Comment by jnehring** [comment]
@andish does an Tilde API endpoint exist that sends the list of language pairs?

**Comment by andish** [comment]
Not yet. but I will create it, after review. It will serve a list of available translation systems: source Lang, target Lang, domain, system id.

**Comment by andish** [comment]
Duplicate of https://github.com/freme-project/e-services/issues/20
