### ISSUE TITLE
postprocessing failes when using mime types for outformat or Accept header

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Broker#154]
moving from https://github.com/freme-project/Documentation/issues/156

**Comment by jnehring** [comment]
This should be fixed. @ArneBinder please try it again.

**Comment by ArneBinder** [comment]
`
curl -X POST --header "Content-Type: application/json" -d "[ {   \"method\": \"POST\",   \"endpoint\": \"http://api-dev.freme-project.eu/current/e-entity/dbpedia-spotlight/documents\",   \"parameters\": {     \"language\": \"en\"   },   \"headers\": {     \"content-type\": \"text/plain\",     \"accept\": \"text/turtle\"   },   \"body\": \"This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium.\" }, {   \"method\": \"POST\",   \"endpoint\": \"http://api-dev.freme-project.eu/current/e-link/documents/\",   \"parameters\": {     \"templateid\": \"3\",     \"filter\": \"extract-entities-only\"   },   \"headers\": {     \"content-type\": \"text/turtle\",  **\"accept\": \"text/xml\"**   } } ]" "http://api-dev.freme-project.eu/current/pipelining/chain?stats=false“
`

leads to this exception:

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-link/documents/",
  "message": "Can only convert to outformat \"text/xml\" when informat is also \"text/xml\"",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1454495757655
}
```

This works:
`
curl -X POST --header "Content-Type: application/json" -d "[ {   \"method\": \"POST\",   \"endpoint\": \"http://api-dev.freme-project.eu/current/e-entity/dbpedia-spotlight/documents\",   \"parameters\": {     \"language\": \"en\"   },   \"headers\": {     \"content-type\": \"text/plain\",     \"accept\": \"text/turtle\"   },   \"body\": \"This summer there is the Zomerbar in Antwerp, one of the most beautiful cities in Belgium.\" }, {   \"method\": \"POST\",   \"endpoint\": \"http://api-dev.freme-project.eu/current/e-link/documents/\",   \"parameters\": {     \"templateid\": \"3\",     \"filter\": \"extract-entities-only\", **\"outformat\": \"xml\"**   },   \"headers\": {     \"content-type\": \"text/turtle\"  } } ]" "http://localhost:8080/pipelining/chain?stats=false"
`

**Comment by ArneBinder** [comment]
fixed.
