### ISSUE TITLE
Error message when filter does not exist

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#156]
When I try to use a filter that does not exist, e.g. through this API call

POST http://api-dev.freme-project.eu/current/e-terminology/tilde?input=Show me the source of the light.&informat=text&source-lang=en&target-lang=de&filter=terms

I get this error message

```
{
    "timestamp": 1454333157311,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "eu.freme.broker.exception.FREMEHttpException",
    "message": "Postprocessing filter failed with status code: 500 (Internal Server Error)",
    "path": "/e-terminology/tilde"
}
```

Please change it to http status code 404 and error message `Cannot find filter "terms"`

**Comment by ArneBinder** [comment]
implemented.
