### ISSUE TITLE
Monitoring emails

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#160]
It seems that when FREME NER fails we get a notification email for each e-Service. We should receive only one email in this case.

**Comment by jnehring** [comment]
Today I ran software updates on our servers. It also installed a new version of Zabbix. When taking a look at the monitoring emails please take a quick look if Zabbix still works.

**Comment by m1ci** [comment]
still plenty of mails are send when some service is down.

**Comment by jnehring** [comment]
@ArneBinder will fix it early next week.

**Comment by m1ci** [comment]
whats that status of this?

**Comment by jnehring** [comment]
We are working on it

**Comment by ArneBinder** [comment]
I have checked all triggers, there are no unwanted dependencies.
So I set the timeouts to 60 sec and increased the amount of retries. I hope this will help.

**Comment by jnehring** [comment]
Arne please try to direct to the URL of FREME dev to a page that you can control, e.g. on FREME dev. Then delete the page and see if you get the the problem described above.

**Comment by jnehring** [comment]
Last week we wanted to run an update of Zabbix which did not work out. Right now the zabbix server is running but the frontend does not work. Will fix this soon.

**Comment by jnehring** [comment]
I updated the frontend also and now it seems to work. We get no monitoring emails but I think this is a configuration issue. The implementer of this task is absent right now so we will work on this task not before the 2nd week of april.

**Comment by jnehring** [comment]
* Milan got no monitoring emails because he was not configured in the email recipient list. This is fixed now.
* Monitoring works better now. After the trigger times have changed we get way less error reports so we think we get less false errors.
* @ArneBinder will prepare logging until the next release and during the release we will switch off freme ner and see how the logging behaves.

**Comment by m1ci** [comment]
I just received an email that there was problem with Tilde's e-Translation. However, I should be subscribed only to e-Entity and e-Link.

**Comment by jnehring** [comment]
> I just received an email that there was problem with Tilde's e-Translation. However, I should be subscribed only to e-Entity and e-Link.

We will need some time to st this up because we have so much other things on the stack right now. When you want to receive only certain mails then you should setup a filter in your client that sorts all other monitoring emails in the trash bin.

**Comment by ArneBinder** [comment]
Increased the zabbix logLevel to log the sent requests (see https://www.zabbix.com/documentation/3.0/manual/web_monitoring#extended_monitoring).

**Comment by ArneBinder** [comment]
This should be fixed. There were templating issues and some macros were not replaced with the correct values, so just `freme-ner` and the external services were queried. But there is [this bug](https://github.com/freme-project/e-services/issues/10).
