### ISSUE TITLE
Support input from URL

### ISSUE THREAD

**Issue by jnehring** [freme-project/Broker#164]
According to the [NIF API specifications](http://persistence.uni-leipzig.org/nlp2rdf/specification/api.html) we need to support the `intype` parameter. This means we support input coming from an URL.

I think we can implement this as a generic filter that becomes active when intype=url is set in an http request. It then downloads the URL and puts the content in the request body. This should be done in a streaming fashion in order to be memory efficient.

In this way we can implement it once and the functionality will be available for every e-Service. We do not have to adapt it for each e-Service.

**Comment by jnehring** [comment]
This should be implemented as a new basic service.

**Comment by bgrusdt** [comment]
This is done in [this issue](https://github.com/freme-project/basic-services/issues/28).

**Comment by jnehring** [comment]
Dublicate of https://github.com/freme-project/basic-services/issues/28
