### ISSUE TITLE
Correct handling of 'waking up' of e-Translation

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/Broker#165]
When a service is temporary unavailable because it is e.g., waking up in the case of e-Translation, is it possible to respond with a status code 503 together with a [Retry-After Header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) that states when the client can try again?

At the moment it gives a 500, but technically speaking that's wrong.

**Comment by andish** [comment]
I could do this on Tilde API side, but then the FREME broker must transver this header to its response.
Currently Tilde API returns 503 Service Unavailable + error msg:
```json

{"Message":"Requested translation system is starting up from standby. Please try again later."}
```

**Comment by jnehring** [comment]
We can implement in the broker that the 503 code will be send to the client when tilde e-Translation responds with 503.

**Comment by pheyvaer** [comment]
And is it also possible to integrate the Retry-After Header?

**Comment by m1ci** [comment]
> And is it also possible to integrate the Retry-After Header?
+1

**Comment by jnehring** [comment]
> And is it also possible to integrate the Retry-After Header?

OK we can do this. @andish do you plan to send the Retry After header also by Tildes API? I think right now Tilde does not send it. Then we can just forward the value of your header which would be IMO the best solution. Otherwise it is no problem to send some constant value - maybe 5 minutes?

**Comment by andish** [comment]
Tilde API will add such header with value. Freme e-service proxy should
only forward the header if present.

2016-02-17 16:19 GMT+02:00 Jan Nehring <notifications@github.com>:

**Comment by andish** [comment]
I have added to Tilde API **Retry-After** header:
![image](https://cloud.githubusercontent.com/assets/11315268/15145798/6d183626-16c0-11e6-9715-b18a373d840b.png)

So this should also be implemented in broker to forward it: if 503 error and also such header exists from underlying service.
First time it says -  retry after 120 seconds, next times 60 s, if not yet ready.

**Comment by jnehring** [comment]
Calling e-Translation in FREME:

```
curl -X POST "http://api-dev.freme-project.eu/current/e-translation/tilde?source-lang=en&target-lang=fr&informat=text&outformat=turtle&input=hello"
```

produces 

```
{
    "exception": "eu.freme.common.exception.ExternalServiceFailedException",
    "path": "/e-translation/tilde",
    "message": "External service failed: {\"Message\":\"Requested translation system is starting up from standby. Please try again later.\"}",
    "error": "Service Unavailable",
    "status": 503,
    "timestamp": 1462886002712
}
```

and status code 503.

So the issue is solved.
