### ISSUE TITLE
creating filters does not work

### ISSUE THREAD

**Issue by m1ci** [freme-project/Broker#166]
Creating filters via the API doc page does not work.
message: Could not create resource: The anonymous user can not own any resource. You have to be logged in to create a resource.

... however we are unable to provide credentials/token.

**Comment by m1ci** [comment]
similar issue when creating templates https://github.com/freme-project/e-Link/issues/67

**Comment by jnehring** [comment]
Is this a dublicate of https://github.com/freme-project/e-Link/issues/67 ?

**Comment by m1ci** [comment]
the same comment in https://github.com/freme-project/e-Link/issues/67 applies also here. Authentication is not clear.

**Comment by jnehring** [comment]
moved to https://github.com/freme-project/technical-discussion/issues/114
