### ISSUE TITLE
e-Terminology: non-queryable terms

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/Broker#167]
The references to the term are not queryable. They are only available on the Tilde website. Therefore, there are not usable in the CKEditor plugin for FREME. Is there a way to fix this?

**Comment by andish** [comment]
Can you explain with some examples?

**Comment by pheyvaer** [comment]
When we use e-Terminology, we get a URI such as this one: `https://term.tilde.com/terms/583318`. When we open this in the browser we get more information. However, there is no way (that we know of) to query the information the information on this page.

**Comment by andish** [comment]
Yes, there is no SPARQL endpoint, but you can download terminology data also in turtle format by adding extension .ttl or adding accept HTTP header.
Try https://term.tilde.com/terms/583318.ttl
