### ISSUE TITLE
e-Terminology output wrong RDF Datatype

### ISSUE THREAD

**Issue by josauder** [freme-project/Broker#170]
The following curl call:
```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" --header "X-Auth-Token: 147b7a6c-a876-444b-99f4-03eaecb406fa" "http://api-dev.freme-project.eu/current/e-terminology/tilde?input=Hello%20this%20is%20text&informat=text&outformat=turtle&source-lang=en&target-lang=de&mode=full"
```
produces nif which includes the RDF type:
 `<http://www.w3.org/1999/02/22-rdf-syntax-ns##XMLLiteral>`

However, the correct type would be:
 `<http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral>` (with one # )

This causes errors when parsing the NIF with a Javascript Library for the [FREME Workflow Editor](http://api-dev.freme-project.eu/freme-workflow-editor)

**Comment by andish** [comment]
Seems that this is a bug TBX2RDF conversion tool. It produces double hash for some categories:
```
 tbx:encodingDesc  "<p type=\"XCSURI\">http://www.ttt.org/oscarstandards/tbx/TBXXCS.xcs</p>"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns##XMLLiteral> ;
```

```
tbx:sourceDesc    "<sourceDesc><p/></sourceDesc>"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns##XMLLiteral> .
```
and

```
tbx:example "noch aus den<hi>Quellen</hi>von ` dpkg"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns##XMLLiteral>;
```

**Comment by jnehring** [comment]
I assume the bug happens on the Tilde server. Can you fix it?

**Comment by andish** [comment]
Yes, TBX2RDF conversion tool is included in Tilde side. Not sure about fixing, but we will take a look.

**Comment by josauder** [comment]
I have found a way to work around it for now - this issue is not that urgent on my side

**Comment by jnehring** [comment]
The bug still occurs. @andish do you plan to provide a solution?

**Comment by andish** [comment]
I will take a look.

**Comment by andish** [comment]
Should be resolved. Please recheck.

**Comment by jnehring** [comment]
works . thank you!
