### ISSUE TITLE
e-Translation: using system id still requires source and target lang

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/Broker#171]
When using the system id of a translation system to use, the source and target language are no longer required (as they are determined by the translation system), however, without providing these languages we can't do a call. This results in a `400`.

```
curl -X POST --header "Content-Type: text/n3" --header "Accept: text/n3" "http://api-dev.freme-project.eu/current/e-translation/tilde?input=This%20is%20my%20house.&informat=text&system=smt-0eba8517-0cf8-43b9-8dc2-ed99b33e56b9"
```

**Comment by jnehring** [comment]
@bgrusdt please implement a smarter input validation in the e-translation service. The user has to specify either source-lang and target-lang or the system id. Maybe you also need to change other parts of the e-translation source code. The source code is [here](https://github.com/freme-project/e-services/blob/master/tilde-services/src/main/java/eu/freme/eservices/tilde/translation/TildeETranslation.java)

**Comment by jnehring** [comment]
@andish we tried to fix this but we have a problem with tilde mt api. We do not find a system id to test this. This curl

```
curl -X POST --header "Accept: text/plain" --header "Content-Type: accept/x-turtle" -d "hello world" "https://services.tilde.com/translation/?system=smt-0eba8517-0cf8-43b9-8dc2-ed99b33e56b9"
```

produces

```
{
    "Message": "No HTTP resource was found that matches the request URI 'http://banzai:91/translation/?system=smt-0eba8517-0cf8-43b9-8dc2-ed99b33e56b9'."
}
```

Can you please provide us with a valid system id?

**Comment by andish** [comment]
Now this is fixed at Tilde side (still in development version).

So curl would be:

``` Curl
curl -X POST -H "Accept: application/rdf+xml" -H "Content-Type: text/plain"  -d 'Hello' "https://services.tilde.com/dev/translation/?system=smt-029976d9-55fa-40ba-91e4-1fe94b4fc26f"
```

**Comment by jnehring** [comment]
@bgrusdt please implement the smarter input validation.

**Comment by bgrusdt** [comment]
Since the tilde-service that works with the system-parameter is only dev version,  I'd wait until they release this functionality. @jnehring what do you think? 
This curl  (calls tilde-dev) fails:

```
curl -X POST -H "Accept: application/rdf+xml" -H "Content-Type: text/plain"  -d 'Hello world' "https://services.tilde.com/dev/translation/?source-lang=en&target-lang=nl"
```

It only works with the system parameter.

**Comment by jnehring** [comment]
Ok lets wait until the feature is released at the Tilde server and the API supports both system parameter and source-lang / target-lang

**Comment by andish** [comment]
This is released. Now it is available also in production environment.
Please note that other parameters not changed - sourceLang and targetLang (differs from FREME server endpoints).

**Comment by jnehring** [comment]
@bgrusdt please implement this in the live version.

**Comment by bgrusdt** [comment]
I have implemented it , [here](https://github.com/freme-project/e-services/blob/master/tilde-services/src/main/java/eu/freme/eservices/tilde/translation/TildeETranslation.java) is the code.

I have also adapted the Unit Test for E-Translation, since the source-lang / target-lang parameter is optional now, [here](https://github.com/freme-project/e-services/blob/master/tilde-services/src/test/java/eu/freme/eservices/tilde/TildeETranslationTest.java) is the updated test.

**Comment by bgrusdt** [comment]
@jnehring I have added the BadRequestException ([see changes](https://github.com/freme-project/e-services/commit/ff0281a2db4c8efd376dce8953ec04ce457609bf)), for the case that neither source+target nor system is specified.  So, can we close this issue?

**Comment by jnehring** [comment]
yes. thanks
