### ISSUE TITLE
Implement Template and Dataset security

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Broker#66]
### Task

* Implement Entity classes for Template and Dataset. See example in [User.java](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/security/database/User.java) and [UserRepository.java](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/security/database/UserRepository.java)
The entity classes only store the name of the dataset (as primary key / id), owner and an integer "accessLevel". Implement two public static final int access levels: "public" and "private". Public means "everybody has access", "private" means "only owner has access".
* Implement unit tests to create, update and delete these entities. See [UserRepositoryTest.java](https://github.com/freme-project/Broker/blob/master/src/test/java/eu/freme/broker/security/database/UserRepositoryTest.java)
* Implement TemplateAccessDecisionVoter and DatasetAccessDecisionVoter. See [UserAccessDecisionVoter.java](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/security/voter/UserAccessDecisionVoter.java). Register it in SecurityConfig.java. DecisionL
* Add the logic to the respective api endpoints during create, update, delete, get dataset / templates. See [UserController.java](https://github.com/freme-project/Broker/blob/master/src/main/java/eu/freme/broker/eservices/UserController.java)
* Create integration tests. See [UserControllerTest.java](https://github.com/freme-project/Broker/blob/master/src/test/java/eu/freme/broker/integration_tests/UserControllerTest.java)

### Read me

* Database configuration: https://github.com/freme-project/technical-discussion/wiki/Configuration-options
* Setup MySQL database using XAMPP to see what happens in the database.
* Setup MySQL workbench and connect to your local mysql database to see whats going on
* [Spring security](http://docs.spring.io/spring-security/site/docs/4.0.2.RELEASE/reference/htmlsingle/), [Spring Authorization Architecture](http://docs.spring.io/spring-security/site/docs/3.0.x/reference/authz-arch.html)
* [Spring JPA tutorial](https://spring.io/guides/gs/accessing-data-jpa/)
* Find out how to do @ OneToOne, @ OneToMany, @ManyToOne, @ManyToMany relationships in the Java Persistence API.

**Comment by jnehring** [comment]
Moved to https://github.com/freme-project/Broker/issues/107 and https://github.com/freme-project/Broker/issues/108
