### ISSUE TITLE
[e-Terminology] Request with invalid source and target lang is successfully processed

### ISSUE THREAD

**Issue by m1ci** [freme-project/Broker#76]
Submitting request with invalid source-lang and target-ang

    curl -v -X POST -H "Accept:" -H "Content-Type:" "http://localhost:8080/e-terminology/tilde?informat=text&outformat=turtle&source-lang=dsadaf&target-lang=gfdfsa&input=food"

Results: the request is successfully processed although the values of the parameters have invalid values. A bad request response with explanation should be returned.

**Comment by andish** [comment]
This is low priority. We could check against ISO 2-letter table, but there are now high priority issues to resolve before.

**Comment by jnehring** [comment]
So when someone sends a text in Urdu which has a ISO code but the terminology engine probably dont support it then IMO you should return status code 400 - bad request. So checking against an ISO table does not help IMO.

**Comment by andish** [comment]
it supports, but does't have any term for Urdu. If the user provide his
terms, he can use this language [with some restriction, but it is possible]

2015-10-09 11:08 GMT+03:00 Jan Nehring <notifications@github.com>:
