### ISSUE TITLE
[e-Terminology][AGROVOC] Why term is not translated in the target language 

### ISSUE THREAD

**Issue by m1ci** [freme-project/Broker#79]
Submitting text with source-lang=EN and target-lang=DE.

    curl -v -X POST -H "Accept:" -H "Content-Type:" "http://localhost:8080/e-terminology/tilde?informat=text&outformat=turtle&source-lang=en&target-lang=de&input=food"

Results: the term food is recognized but German translation is not provided. Why?

**Comment by andish** [comment]
Yes, the service is up and running. 
As discussed in Turin, translations of terms not needed if references are present.
