### ISSUE TITLE
minor bugs in eservices caused by integration of normalizeNif

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/Broker#92]
similar to #90 there are minor bugs in some eservices: the short forms of the nif parameters aren't considered, because merging of them is done after normalizeNif sometimes. Proposel: integrate this merging to normalizeNif in the BaseRestController, because it is needed everywhere, and consequently apply normalizeNif to all requests handling nif (for instance, POST /e-link/templates misses it). @jnehring should I do this?
Furthermore there should be an error response with HttpStatus.BAD_REQUEST, if something failes by using normalizeNif.
In some cases (POST /e-link/templates) the body is checked for empty content, but normalizeNif (in particular NIFParameterFactory.constructFromHttp) checks just, if body and input are null. What should be prefered?

**Comment by jnehring** [comment]
> DBpediaSpotlight: 
POST /e-link/documents uses normalizeNif(), but still uses postBody instead of parameters.getInput() --> ERROR

This bug will be fixed in #115.

> POST/GET /e-entity/freme-ner/documents uses normalizeNif(), but short forms aren't considered and postBody is used instead of parameters-getInput() --> ERROR

This bug will be fixed in #116.

@ArneBinder when you write e.g. `POST /e-link/templates does not use normalizeNif()` do you report an error? Did you manually test if the endpoints support long and short forms and all the nif specifications?

**Comment by ArneBinder** [comment]
There was no error, but for consistency reasons I would recommand to use the same mechanism for all endpoints handling similar parametersets. I think this could help to keep the code clean and is less error prone.

**Comment by jnehring** [comment]
>  I think this could help to keep the code clean and is less error prone.

You are right but: We will not fix this now. When an error occurs or when we touch the codes anyways then we can implement this. But we will not exchange bug-free and well tested code with new code just because the new code is cleaner.
